### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by MegaH01** [phrutis/Rotor-Cuda#18]
Ubuntu 20.04 with Cuda 11 (2070 Card).  Unable to compile.  Any ideas?

~/Rotor-Cuda/linux# make gpu=1 CCAP=75 all
cd obj &&       mkdir -p GPU
cd obj &&       mkdir -p hash
g++ -DWITHGPU -m64 -mssse3 -Wno-write-strings -O2 -I. -I/usr/local/cuda-11.0/include -o obj/Main.o -c Main.cpp
Main.cpp: In function â€˜int main(int, char**)â€™:
Main.cpp:523:2: error: â€˜consoleâ€™ was not declared in this scope
  523 |  console con(bok1, bok2);
      |  ^~~~~~~
Main.cpp:524:2: error: â€˜HANDLEâ€™ was not declared in this scope
  524 |  HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
      |  ^~~~~~
Main.cpp:525:26: error: â€˜hConsoleâ€™ was not declared in this scope
  525 |  SetConsoleTextAttribute(hConsole, color);
      |                          ^~~~~~~~
Main.cpp:525:2: error: â€˜SetConsoleTextAttributeâ€™ was not declared in this scope
  525 |  SetConsoleTextAttribute(hConsole, color);
      |  ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:71: obj/Main.o] Error 1

**Comment by phrutis** [comment]
For CPU [Rotor-Cuda](https://disk.yandex.ru/d/-BUmU2wcoSAObQ) - [make](https://github.com/phrutis/Rotor-Cuda/tree/main/linux#readme)

**Comment by phrutis** [comment]
For your assembly, replace 2 files in the Fialka folder Rotor.cpp and Main.cpp with Rotor.cpp and Main.cpp from the linux folder

**Comment by Radar-7528** [comment]
Бро! ты все чаты закрыл???

**Comment by phrutis** [comment]
Это не чаты, а вопросы.

**Comment by MegaH01** [comment]
> For CPU [Rotor-Cuda](https://disk.yandex.ru/d/-BUmU2wcoSAObQ) - [make](https://github.com/phrutis/Rotor-Cuda/tree/main/linux#readme)

Sorry did not work.

**Comment by MegaH01** [comment]
> For your assembly, replace 2 files in the Fialka folder Rotor.cpp and Main.cpp with Rotor.cpp and Main.cpp from the linux folder

Sorry did not work.  Same compile errors

**Comment by phrutis** [comment]
Make [KeyHunt-Cuda](https://github.com/kanhavishva/KeyHunt-Cuda)
