### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by Landovil** [phrutis/Rotor-Cuda#19]
Hello. What would be the best search command? 
 I have 1660Ti - 468Mk/s. I use 1up.bin

Rotor-Cuda.exe -g - - gpui 0 - - gpux 256,256 - -range 7777777777:8888888888 -m addresses - - coin BTC -r 250 - i 1up.bin

And

Rotor-Cuda.exe -g --gpui 0 -m addresses --coin BTC -r 20 -n 252 -z 256 -i 1up.bin

Photo
![IMG_20220128_134416](https://user-images.githubusercontent.com/95962082/151524457-82ebc25d-cac9-4ff0-9dd0-7731e3bcf872.jpg)

**Comment by Landovil** [comment]
Возник вопрос.
Как лучше искать? с базой 1up.bin

Командой в диапазоне 7777777777:8888888888

Rotor-Cuda.exe -g - - gpui 0 - - gpux 256,256 - -range 7777777777:8888888888 -m адреса - - coin BTC -r 100 - i 1up.bin

Или рандомом
Rotor-Cuda.exe -g - - gpui 0 - - gpux 256,256 -m адреса - - coin BTC -r 100 - i 1up.bin

**Comment by phrutis** [comment]
7777777777:8888888888 здесь ничего нет.
С рандомом есть шанс найти, такой как выиграть в лотерею.
Лучше ищи [пазл64](https://privatekeys.pw/puzzles/bitcoin-puzzle-tx) - это самый маленький диапазон, соответственно шансы найти выше

**Comment by Landovil** [comment]
> 7777777777:8888888888 здесь ничего нет. С рандомом есть шанс найти, такой как выиграть в лотерею. Лучше ищи [пазл64](https://privatekeys.pw/puzzles/bitcoin-puzzle-tx) - это самый маленький диапазон, соответственно шансы найти выше

Напиши пожалуйста команду. А то укажу что-то не так обидно будет потратить время впустую

**Comment by Landovil** [comment]
> 7777777777:8888888888 здесь ничего нет. С рандомом есть шанс найти, такой как выиграть в лотерею. Лучше ищи [пазл64](https://privatekeys.pw/puzzles/bitcoin-puzzle-tx) - это самый маленький диапазон, соответственно шансы найти выше

?

**Comment by phrutis** [comment]
На расковырку нужно 300 лет на скорости 1000Mkey/s
Если использовать 1000 карт и найти быстрее. 
Пазл не перекроет расходы + электричество, майнинг будет актуальнее.
```Rotor-Cuda.exe -g - - gpui 0 - - gpux 256,256 -r 100 -m address --coin BTC --range 8000000000000000:ffffffffffffffff 16jY7qLJnxb7CHZyqBP8qca9d51gAjyXQN```
Надоест, крути другой [пазл](https://privatekeys.pw/puzzles/bitcoin-puzzle-tx)

**Comment by phrutis** [comment]
На расковырку нужно 300 лет на скорости 1000Mkey/s
Если использовать 1000 карт и найти быстрее. 
Пазл не перекроет расходы + электричество, майнинг будет актуальнее.
```Rotor-Cuda.exe -g --gpui 0 --gpux 256,256 -r 100 -m address --coin BTC --range 8000000000000000:ffffffffffffffff 16jY7qLJnxb7CHZyqBP8qca9d51gAjyXQN```
Надоест, крути другой [пазл](https://privatekeys.pw/puzzles/bitcoin-puzzle-tx)
