### ISSUE TITLE
выход за диапазон

### ISSUE THREAD

**Issue by forevox** [phrutis/Rotor-Cuda#25]
Привет. почему-то при указании диапазона 64 bit например, выходит за него при сканировании, возможно в других диапазонах
Команда      Rotor-Cuda.exe -g --gpui 0 -m addresses --coin BTC -b -r 5 -n 64 -i hex160sorted.bin
![Screenshot_5](https://user-images.githubusercontent.com/29515115/153195245-032e95fb-731d-4719-b42e-3ea651c5d59c.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/29515115/153195270-2c1796e8-eae6-4ccb-b66f-636d029c052e.jpg)

**Comment by phrutis** [comment]
Это старый рандомный генератор от VanitySearch у него погрешность ~4 бита.
Для точности используй --range 8000000000000000:b777777777777777

**Comment by forevox** [comment]
Понял, спасибо
