### ISSUE TITLE
Set GPU power consumption and fan control

### ISSUE THREAD

**Issue by advanpix** [phrutis/Rotor-Cuda#31]
Thank you for nice software!

I would like to propose one (very) important feature.
When software is running on GPU for a long time GPU gets hot and draws significant wattage. 
But all the power consumption is not really needed and it can be optimized without decrease in speed of computations.

To handle this, mining software (e.g. gminer, t-rex, etc.) allows user to setup power limit and fan level. 
For example, t-rex has argument "--pl X" and  "--fan Y".

This functionality would a natural and very useful addition to Rotor-Cuda. 
GPU power & fan control can be done using NVML library, which is part of CUDA toolkit. 
For example, "nvmlDeviceSetPowerManagementLimit" function can be used to setup the power usage in %.

Let me know if you have plans to add it.

**Comment by phrutis** [comment]
Many have built-in programs for adjusting the GPU. If they are not enough in the PC power settings, select performance (quiet, min, economy), this will reduce the frequency of the gpu and the temperature will drop.

**Comment by advanpix** [comment]
Well, certainly there is third-party programs like this. 
But manual adjustment is very inconvenient, especially if you try using Rotor-Cuda on several computers or on remote computers for a long time.

That is why all miner software include this functionality, as this allows all-in-one control using command line in various usage scenarios. Looks like this functionality requires just few calls to functions from NVML.DLL.

**Comment by phrutis** [comment]
My laptop has a built-in Armory Crate program, there is a manual setting for each of the two coolers. There is a cooling pad of 5 coolers.
Can you build these parameters into Rotor-Cuda? Perhaps someone will find them useful.

**Comment by advanpix** [comment]
Your example is not legit.

CUDA API provides standard way to manage power limit and fan of any NVIDIA GPU.
Adding this functions are commonly accepted in programs targeted for long-time computations. It is a necessity to save GPU lifespan. 

Rotor-Cuda is obviously belongs to this category and it needs this functionality. 
If you don't understand it now - you will understand it later after the first burnt GPU.

**Comment by phrutis** [comment]
I don't see the point in doing anything with the program.
For Nvidia, there are a lot of websites on the Internet, including official and built-in ones. Anyone who needs can download and manage the GPUs settings themselves.
Rotor-Cuda does not heat the card much, unlike some games.

**Comment by advanpix** [comment]
As I said, doing manual settings on several computers, especially remote is not an option.
Do you run the program on something more serious than one laptop?
Did you check GPU temperature (core/mem) after running Rotor-Cuda for a few hours (e.g. using GPU-Z)?

Rotor-Cuda does exactly what mining programs do - very intensive CUDA computations. 
All of them allow power limits and fan control because it is crucial in GPU computations. That is really not a question for discussion. This is simple understanding and experience with working with GPU.

Btw, on RTX 8000 temperature gets to 80/95 C after running Rotor-Cuda for 30 minutes or so.
Temperature can be reduced by setting up the power limit for GPU (~60%). That is pretty standard situation.

**Comment by phrutis** [comment]
Can you make these settings in the program?
