### ISSUE TITLE
Rotor cuda special edition

### ISSUE THREAD

**Issue by saifzaidi1** [phrutis/Rotor-Cuda#48]
Dont know from where I downloaded the special edition , it has the -r1 =1.000.000 it changes keys randomly, i have no issues with the prompt but for some reason it has a virus and my antivirus deletes it. Is it a legit one or not?
![image](https://user-images.githubusercontent.com/108569566/188303903-1e97273e-784a-42f9-b3ad-c830884bf77b.png)

**Comment by phrutis** [comment]
I made this program at the request of the user.
I don't know where you got it from, if in doubt you can build from source.
