### ISSUE TITLE
--range 1:1fffffffff      --range 100000000:fffffffff00000000

### ISSUE THREAD

**Issue by DFKTYNBY967** [phrutis/Rotor-Cuda#49]
Доброго дня.
Режим     --range 1:1fffffffff                                              от  1-32 бит    начинает считать с  1 го бита  просчитывается за 15 мин.
Режим     --range 100000000:1fffffffff00000000              от  32-64 бит  начинает считать снова  с  1 го бита ,  а не с 32 го бита 

какую команду нужно ввести чтобы  ROTOR -CUDA считал не все 64 бита, а только участок в 32 бита ---от 32 до 64 

000000000000000000000000000000000000000000000000ffffffff00000000

**Comment by phrutis** [comment]
cpu или gpu?
Напишите строку запуска, возможно вы допустили ошибку?
--range ffffffff:ffffffffffffffff

**Comment by DFKTYNBY967** [comment]
Это команда. 32-64 бит
./Rotor-Cuda.exe -g --gpui 0 -m addresses --coin BTC --range f0000000:ffffffff00000000 -i btc.bin -n 1 -d 4 
![Скриншот 09-09-2022 230202](https://user-images.githubusercontent.com/68655916/189434269-adeb4dfb-098f-4eb3-84f1-26046732809a.jpg)
проценты вообще не движутся

А это команда. 1-40 бит 
./Rotor-Cuda.exe -g --gpui 0 -m addresses --coin BTC --range 1:ffffffffff -i btc.bin -n 1 -d 4
![Скриншот 09-09-2022 230919](https://user-images.githubusercontent.com/68655916/189435619-cf88d4d4-b324-4ee3-a079-70ceb8e49830.jpg)
здесь за 30 сек  пройдено 14 %

**Comment by DFKTYNBY967** [comment]
Видиокарта.

**Comment by DFKTYNBY967** [comment]
C процессором таже история.

**Comment by phrutis** [comment]
1. Нужно указазать  --gpux 256,256 это 65536 потоков.
2. Примерно по времени твоя задача 500 лет.
Подожли месяц другой будет обновлятся всё.

Не знаю что там можно искать? 
Если тебе нужен пазл64 вот ключ F7051F27B09112D4

**Comment by DFKTYNBY967** [comment]
АГА СЕГОДНЯ НОЧЬЮ ЗАБРАЛИ .УЖЕ ВСЕ В КУРСЕ .МОИ ПОЗДРАВЛЕНИЯ!!!

**Comment by DFKTYNBY967** [comment]
-0.64032959 BTC
Хэш
[9c1d797c34e3b04f9b721bac45fe3a410393bdd25d169bc62dcbca46b069fa9f](https://www.blockchain.com/ru/btc/tx/9c1d797c34e3b04f9b721bac45fe3a410393bdd25d169bc62dcbca46b069fa9f)
2022-09-10 01:47

**Comment by DFKTYNBY967** [comment]
СПАСИБО !БУМ ЖДАТЬ ОБНОВЛЕНИЯ.
